version: '3.8'

services:
  web:
    build: ./
    command: |
      sh -c 'pipenv run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PASSWORD=1234
      - STAGE=dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jason
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hello_fastapi_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
